# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'
plugin 'cocoapods-art', :sources => [
  'cocoapods-identy-finger'
]
source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'

    pod 'KeychainSwift', '~> 19.0'
    pod 'lottie-ios', '= 3.2.3'
    pod 'Alamofire', '= 4.8.1'
    pod 'AlamofireImage'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper', '~> 5.2.0'

    def contactlessUI
      pod 'Identy', '~> 5.1.1'
    end

    target 'iosApp' do
    xcodeproj 'iosApp.xcodeproj'
      contactlessUI
    end


end

#post_install do |installer|
# installer.pods_project.targets.each do |target|
#  target.build_configurations.each do |config|
#   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
#  end
# end
#end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      if config.name == 'Test'
          config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      end
    end
  end
end
